/** Shared UI copy. Nav uses Painel; GRID is the product name. */

export const COPY = {
  landingMetaTitle: "GRID — lista, qualificação e CRM",
  landingHeadline:
    "Monte a lista, encontre quem decide e ligue — com CRM\u00a0incluído.",
  landingPromessa:
    "Você escolhe o nicho e a cidade. Sai a lista na ordem de quem ligar, com telefone da empresa e o nome do sócio. Salve a lista, qualifique, e os leads entram no CRM.",
  landingPrimeiraVez: "Em minutos você sai com a lista pronta para ligar.",
  landingCtaStart: "Começar grátis",
  landingCtaPlans: "Ver planos",
  landingNavHow: "Como funciona",
  landingNavQualify: "Qualificação",
  landingNavCrm: "CRM",
  landingNavPlans: "Planos",
  landingHowEyebrow: "Como funciona",
  landingHowTitle: "Busque, monte a lista e ligue no mesmo\u00a0dia",
  landingHowStep1Title: "Escolha o nicho e a região",
  landingHowStep1Body:
    "Você define o mercado e a cidade. A busca é na Receita — não em mapa. MEI fica de fora por padrão.",
  landingHowStep2Title: "A lista sai na ordem de quem ligar",
  landingHowStep2Body:
    "Cada linha traz telefone da empresa e o nome do sócio que decide. Ligue de cima para baixo.",
  landingHowStep3Title: "Salve, qualifique e envie ao CRM",
  landingHowStep3Body:
    "Você salva a lista e qualifica. O lote entra sozinho no quadro, sem copiar lead por lead.",
  landingMeiNote:
    "MEI fica de fora da busca padrão: o faturamento ainda não entra no filtro, e em geral há menos espaço para investir.",
  landingPainEyebrow: "O que trava a ligação",
  landingPainTitle: "Três tarefas lentas. A lista resolve as\u00a0três.",
  landingPain1Title: "Montar a lista",
  landingPain1Body:
    "Buscar empresa por empresa, copiar telefone, jogar na planilha. Horas antes da primeira ligação.",
  landingPain2Title: "Achar quem decide",
  landingPain2Body:
    "O telefone da empresa não basta. Sem o nome do sócio, você cai na recepção ou no contador.",
  landingPain3Title: "Qualificar o digital",
  landingPain3Body:
    "Site, Instagram, Google — saber se a empresa está viva e como ela aparece online dá trabalho. E muda a ligação.",
  landingBenefitsEyebrow: "O que vem na lista",
  landingBenefitsTitle: "Telefone, quem decide, ordem de ligação",
  landingBenefit1Title: "Telefone da empresa",
  landingBenefit1Body:
    "Avisa quando o número é da contabilidade, não de quem decide.",
  landingBenefit2Title: "Sócio que decide",
  landingBenefit2Body:
    "O nome de quem pode fechar já vem na linha, para a primeira ligação.",
  landingBenefit3Title: "Ordem de quem ligar",
  landingBenefit3Body:
    "A lista já vem ranqueada. Você liga de cima para baixo.",
  landingQualifyEyebrow: "Qualificação",
  landingQualifyTitle: "Os ativos da empresa, antes de ligar",
  landingQualifyBody:
    "Cruzamos site, redes e Google com o cadastro. O que a empresa mostra — e o que falta — muda a abordagem. Sem site ou Instagram é oportunidade para quem vende marketing.",
  landingQualifyPreviewLabel: "Assim sai a qualificação",
  landingQualifyOpportunity: "Oportunidade",
  landingQualifyMissingSeal: "Não possui",
  landingCrmEyebrow: "CRM",
  landingCrmTitle: "A lista qualificada já entra no quadro",
  landingCrmBody:
    "Salvou e qualificou: o lote inteiro cai em Entrada. Você liga, anota e segue o contato — sem planilha paralela.",
  landingCrmPreviewLabel: "Assim entra no CRM",
  landingPlansEyebrow: "Planos",
  landingPlansTitle: "Escolha o plano e comece pela lista",
  landingPlansBody:
    "No Treino livre você busca, vê a lista e qualifica 25\u00a0empresas. A mensalidade libera o CRM e o volume do mês. Qualificar custa 1 crédito. Ligar pela ficha é grátis. Exportar a planilha custa mais.",
  landingPlansMore: "Recargas e detalhes",
  landingPlansCtaFree: "Começar grátis",
  landingPlansCtaPaid: "Assinar",
  landingPlansCtaSoon: "Em breve",
  landingPlansFeatured: "Mais escolhido",
  landingFinalTitle: "Comece pela lista. Ligue no mesmo\u00a0dia.",
  landingFinalBody:
    "Crie a conta, escolha o nicho e saia com telefone e o nome de quem decide.",
  landingPreviewLabel: "Assim sai a lista",
  landingPreviewFilter: "Clínicas · Curitiba",
  landingPreviewBuilding: "Montando a lista",
  landingPreviewReady: "Lista pronta",
  landingSignedInCta: "Abrir o GRID",
  landingFooterNote: "Um produto Mundo Pódium",
  loginConfirm:
    "Enviamos um link de confirmação. Veja a caixa de entrada e o spam. Se o e-mail estiver errado, volte e cadastre de novo. Se você já tem conta, entre.",
  loginRecover:
    "Se houver conta neste e-mail, você recebe o link para definir a senha.",
  entrarSignupLane: "Criar conta",
  entrarLoginLane: "Já tenho conta",
  entrarToggleLogin: "Entrar",
  entrarToggleSignup: "Criar conta",
  entrarTrialBadge: "Treino livre",
  entrarTrialHint: "Sem\u00a0cartão",
  entrarSignupHook:
    "Buscar e ver a lista é grátis. 25\u00a0qualificações, sem\u00a0cartão.",
  entrarLoginHook: "Entre para continuar a lista de hoje.",
  entrarLoginCta: "Entrar no GRID",
  entrarGoogleCta: "Continuar com Google",
  entrarEmailCta: "Usar e-mail",
  entrarOrDivider: "ou",
  boxPlatformCoupon:
    "Você assina o Mundo Pódium. Use o cupom PILOTO — vale só para assinantes ativos da\u00a0Plataforma.",
  boxPlatformTrialEnded:
    "Os 30 dias do Piloto acabaram. Assine o Piloto para continuar. Recarga só soma crédito — não reabre o\u00a0CRM.",
  cnae: "Código da atividade da empresa na Receita.",
  decisor: "Sócio que pode decidir (quadro de sócios).",
  outrasPortas: "Outros contatos",
  outrasPortasHint:
    "Quadro e nomes no site — outras pessoas além do decisor.",
  quadroReceita: "Quadro",
  nomesNoSite: "No site",
  qualifiqueNomesSite: "Qualifique para ver nomes no site.",
  nenhumNomeSite: "Nenhum diretor ou contato nomeado no site.",
  portaRecomendada: "Melhor contato",
  score: "Ordem de quem ligar primeiro.",
  simples: "Regime Simples Nacional.",
  matriz: "Sede da empresa, não filial.",
  minutoDeOuro:
    "Briefing do mercado na hora da ligação: dor do ramo, meses de pico e o melhor horário. Site e redes ficam na Qualificação.",
  clarezaDeMercado:
    "Na ficha, o briefing da ligação já traz a dor do ramo, os meses de pico e o melhor horário.",
  anatomiaDaLigacao:
    "O perfil monta quem você é na ligação (nome, empresa, cidade e promessa). Na ficha, o briefing do nicho — dor, calendário e uma pergunta — é para ter em mente, não para ler no telefone.",
  qualificacaoFicha:
    "Site, redes e Google desta empresa — o que tem e o que falta. Isso muda a abordagem; não é o briefing da ligação.",
  b2c: "Vende para o consumidor final na cidade.",
  b2b: "Vende para outras empresas — indústria, serviços, logística e atacado.",
  emailGratuito: "Gmail, Hotmail e outros provedores pessoais.",
  emailSharedTitle: "E-mail compartilhado",
  emailSharedBody:
    "Aparece em várias empresas na Receita — costuma ser do contador ou do grupo, não o contato direto desta empresa.",
  emailAccountantTitle: "Domínio de contabilidade",
  emailAccountantBody:
    "O endereço parece de escritório contábil. Não use como e-mail ou site da marca.",
  emailSharedAccountantTitle: "E-mail compartilhado (possível contabilidade)",
  emailSharedAccountantBody:
    "Este endereço está em mais de uma empresa e o domínio parece de escritório contábil — provavelmente não é o contato direto desta empresa.",
  emailFreeTitle: "Provedor gratuito",
  emailFreeBody:
    "Gmail, Hotmail e similares — confiança menor para contato comercial.",
  dominioProprio: "E-mail no domínio da empresa, não Gmail ou Hotmail.",
  especialidade: "O nicho da sua lista — o mercado que você aborda.",
  area: "O grupo desse nicho, gravado na primeira lista.",
  comoChama: "Como você se apresenta na ligação.",
  setupIdentityTitle: "Quem liga",
  setupIdentityHint:
    "Isso entra na abertura da ligação. Depois você monta a primeira\u00a0lista.",
  setupGridTitle: "Sua primeira lista",
  setupGridHint:
    "Escolha o nicho e a região. A lista sai pronta para ligar.",
  setupContinue: "Continuar",
  setupGenerate: "Montar a lista",
  setupNeedIdentity: "Preencha nome, empresa, cidade e a promessa.",
  setupNeedNiche: "Escolha um nicho.",
  setupNeedRegion: "Escolha um estado.",
  setupWelcomeBack: "Bem-vindo de volta",
  promessa: "Uma linha do que você entrega.",
  promessaCompromisso:
    "O compromisso do dia. Entra no motivo, na consideração e no convite da reunião.",
  tratamento: "Artigo na abertura: o, a ou e.",
  novaLista: "Nova lista",
  continuarLista: "Continuar lista",
  qualificar: "Qualificar",
  qualificarMetaHoje: "Qualificar a meta de hoje",
  exportCrmIncluso: "No CRM do GRID isso já está incluído.",
  exportar: "Exportar",
  maisAcoes: "Mais",
  exportNeedsQualify:
    "Qualifique pelo menos uma empresa para exportar. No CRM do GRID isso já está incluído.",
  exportCostEyebrow: "Ação custosa",
  exportCostCalculating: "Calculando o custo…",
  exportCostTitlePush: "Enviar lista",
  exportCostTitleExport: "Exportar {format}",
  exportCostCompaniesOne: "Esta ação inclui 1 empresa já qualificada.",
  exportCostCompaniesMany:
    "Esta ação inclui {n} empresas já qualificadas.",
  exportCostDebit: "Vai debitar {credits}.",
  exportCostDetailOne: "1 empresa × {unit}.",
  exportCostDetailMany: "{n} empresas × {unit}.",
  exportCostAlreadyBilledOne: "1 já cobrada — não cobramos de novo.",
  exportCostAlreadyBilledMany: "{n} já cobradas — não cobramos de novo.",
  exportCostBalance: "Você tem {credits}.",
  exportCostNothing: "Nada a debitar — esta lista já foi cobrada.",
  exportCostConfirmExport: "Confirmar exportação",
  exportCostConfirmPush: "Confirmar envio",
  exportCostExporting: "Exportando…",
  exportCostSending: "Enviando…",
  exportCostCancel: "Cancelar",
  exportCostRecarregar: "Recarregar",
  qualificarMarque:
    "Selecione as empresas para buscar site, redes e Google. Custa 1 crédito cada. Telefone e nome saem mais confiáveis, e a ordem da lista pode se ajustar.",
  qualificarEstaEmpresa: "Qualificar esta empresa",
  atualizarQualificacao: "Atualizar",
  atualizarQualificacaoHint:
    "Mantém o resultado atual e busca de novo site, redes e Google. Consome 1 crédito — só quando você pedir.",
  atualizandoQualificacao: "Atualizando…",
  corrigirQualificacao: "Corrigir",
  inserirQualificacao: "Inserir",
  limparQualificacao: "Limpar",
  salvarQualificacao: "Salvar",
  cancelarQualificacao: "Cancelar",
  corrigirQualificacaoHint: "Correção sua — não veio da Receita.",
  qualificarFichaLead: "Ver site, redes e Google desta empresa.",
  qualificarFichaLeadHint:
    "Se você ainda não qualificou, site e redes aparecem em branco. Isso não quer dizer que a empresa não tenha presença online.",
  qualificarBeneficioTelefone:
    "Telefone conferido (site × Receita) e selo de conferência",
  qualificarBeneficioContato:
    "Contato e decisor mais atuais que o cadastro sozinho",
  qualificarBeneficioDigital:
    "Site, redes e o que falta — para mudar a abordagem, não o pitch",
  fichaQualifyQualified: "Qualificada",
  fichaQualifyScanning: "Qualificando",
  fichaSealLiveSite: "No ar",
  fichaSealLiveSocial: "Ativo",
  fichaSealLiveGoogle: "Atualizado",
  fichaSealGmbComplete: "Completo",
  fichaSealGmbPartial: "Parcial",
  fichaSealGmbThin: "Incompleto",
  fichaSealUnverified: "A confirmar",
  fichaSealPending: "Ainda não vimos",
  fichaSealScanning: "Buscando",
  fichaSealToolLive: "No site",
  fichaSealToolMissing: "Não encontrada",
  boxSemLista:
    "Salve uma lista para começar o dia. Depois você qualifica e liga — salvar a lista não substitui a\u00a0ligação.",
  boxPistaFechada: "Sem lista salva",
  boxSequenciaHintZero:
    "Nenhuma sequência ainda. Ligue hoje para começar.",
  boxSequenciaHintOne:
    "Você está numa sequência de 1 dia fazendo ligações.",
  boxSequenciaHintMany:
    "Você está numa sequência de {n} dias fazendo ligações.",
  boxAcessoHint:
    "Seu saldo cobre {days} {dayWord} de meta ({goal} fichas por dia). {credits} créditos · {cost} por ficha.",
  boxAcessoHintZero:
    "Saldo insuficiente para um dia de meta ({goal} fichas). {credits} créditos · {cost} por ficha.",
  boxAcessoHintLocked:
    "A mensalidade segue a qualificação e abre o CRM. Recarga só soma crédito — não reabre o acesso.",
  boxListasHintZero: "Você não tem listas salvas.",
  boxListasHintOne: "Você possui 1 lista salva.",
  boxListasHintMany: "Você possui {n} listas salvas.",
  boxEstrutura: "Estrutura",
  boxPularEtapa: "Pular etapa",
  ajustarBusca: "Ajustar busca",
  ajustar: "Ajustar",
  ajustarNichoQualidade: "Ajustar nicho e qualidade",
  verNovoGrid: "Ver nova lista",
  verResultados: "Ver resultados",
  listaOriginalNaoSome: "A lista original não some",
  largadaNovaHint:
    "Monte a lista em 3 passos: o que buscar, onde, e a qualidade do contato.",
  largadaContinuarHint:
    "As escolhas desta sessão ainda estão aqui. Continue nos 3 passos — nada foi apagado.",
  largadaAjustarHint:
    "As escolhas desta lista já estão preenchidas. Mude nicho, região ou qualidade e gere uma lista nova — a lista original não\u00a0some.",
  gridEmptyAdjust:
    "Nenhum lead nesta busca. Ajuste nicho, região ou qualidade — as escolhas atuais já vêm\u00a0preenchidas.",
  gridLigarOrdem: "ligar nesta ordem",
  salvarLista: "Salvar lista",
  salvarNaPista: "Salvar no CRM",
  salvarEstaLista: "Salvar esta lista",
  renomearLista: "Renomear lista",
  listaSalva: "Salva",
  salvarMotivoListas: "Fica em Minhas listas para abrir de novo",
  salvarMotivoOrdem: "A ordem P1, P2, P3 continua",
  salvarMotivoCrm: "Depois de salvar, os qualificados entram sozinhos no CRM",
  tirarDaLista: "Tirar da lista",
  tirarDaListaConfirm: "Tirar esta empresa da lista? O negócio no CRM fica.",
  listaDaVolta: "Lista do dia",
  listaDaVoltaFallback: "Esta lista não tem P novo — usando outra.",
  empresaForaDaBase: "Este CNPJ não está nesta base da Receita.",
  empresasPlaceholder: "Nome, fantasia ou CNPJ",
  empresasMinChars: "Digite nome, fantasia ou CNPJ.",
  empresasListaCta: "Buscar {nicho} na lista",
  empresasListaHint: "Monta a lista por atividade, com telefone e quem decide.",
  tirarDasListas: "Tirar das listas",
  listasNaoSalvas: "Não salvas",
  listasRascunho: "Rascunho",
  listasSalvasHint:
    "Listas que você guardou para ligar de novo. Tirar da tela não exclui a lista salva.",
  listasNaoSalvasHint:
    "Até 3 rascunhos: você só abre de novo. Para guardar de verdade ou excluir, salve a lista.",
  listasMostrarMais: "Mostrar mais · {n}",
  listasLeadOne: "lead",
  listasLeadMany: "leads",
  crmNav: "CRM",
  crmTitle: "CRM",
  crmHint:
    "Arraste o card, registre a ligação e marque a próxima ação.",
  crmOpening: "Abrindo CRM…",
  crmOpeningNav: "Abrindo…",
  crmLoadingNicho: "Abrindo nicho…",
  crmAddDeal: "Adicionar negócio",
  crmAddDealSearchPlaceholder: "Nome, fantasia ou CNPJ",
  crmAddDealNoHits: "Busque pelo nome, fantasia ou CNPJ para selecionar a empresa.",
  crmAddDealNeedCompany: "Selecione uma empresa da busca.",
  crmAddDealNeedFicha: "Puxe a ficha para conferir antes de adicionar.",
  crmAddDealAlreadyInPipeline: "Esta empresa já está neste nicho.",
  crmAddDealReview: "Conferir ficha",
  crmAddDealCnae: "CNAE",
  crmOpenExistingDeal: "Abrir negócio existente",
  crmPullFicha: "Puxar ficha",
  crmPullFichaLoading: "Qualificando ficha…",
  crmPullFichaCredit: "1 crédito",
  crmPullFichaHint:
    "Qualifica a ficha e conta no saldo. Confira os dados antes de mandar para o CRM.",
  crmPullFichaDone: "Ficha conferida",
  crmPipelineSelectLabel: "Pipeline",
  crmStageSelectLabel: "Etapa",
  crmUnlinkCompany: "Desvincular",
  crmAdjustCadence: "Ajustar cadência",
  crmNoActivity: "Sem próxima ação",
  crmLogCall: "Salvar",
  crmLogCallHint:
    "Atualiza a próxima ligação no card. Não conta na meta.",
  crmSchedule: "Só agendar próxima",
  crmScheduleHint:
    "Atualiza data e ação no card. Não registra a ligação.",
  crmComposerPlaceholder: "O que considerar nesta ação?",
  crmHistoryTitle: "Histórico",
  crmHistoryTodo: "A fazer",
  crmHistoryTodoToday: "Hoje",
  crmHistoryTodoOverdue: "Atrasada",
  crmMarkDone: "Concluir",
  crmHistoryEmpty: "Nada registrado ainda. Cada ligação e ação fica aqui.",
  crmCreatedAt: "Criada",
  crmSaveHistory: "Salvar",
  crmNoDeadline: "Sem prazo",
  crmSetDeadline: "Agendar prazo",
  crmDeadlineLabel: "Prazo",
  crmTimeLabel: "Horário",
  crmToday: "Hoje",
  crmTomorrow: "Amanhã",
  crmWeekLater: "1 semana depois",
  crmPrevStages: "Fases anteriores",
  crmNextStages: "Próximas fases",
  crmPeopleTitle: "Pessoas",
  crmAddPerson: "Adicionar pessoa",
  crmPersonEmail: "E-mail",
  crmPersonPhone: "Telefone",
  crmCompanyPhone: "Telefone da empresa",
  crmActions: "Ações",
  crmCallNow: "Ligar",
  crmWhatsappNow: "WhatsApp",
  crmNoteNow: "Nota",
  crmEmailNow: "E-mail",
  crmNoPhone: "Adicione um telefone para ligar.",
  crmOutcomeOpen: "Em andamento",
  crmOutcomeWon: "Ganho",
  crmOutcomeLost: "Perdido",
  crmDealAmount: "Valor",
  crmDealAmountHintOpen: "Entra como previsão no painel.",
  crmDealAmountHintWon: "Entra no faturado do painel.",
  crmDealAmountHintLost: "Não entra no faturado.",
  crmDealAmountNeeded: "Informe o valor para contar no faturado.",
  crmDealAmountPlaceholder: "0,00",
  crmWinChegada: "Chegada",
  crmWinP1: "P1",
  crmShowClosed: "Ganhos / perdidos",
  crmHideClosed: "Só em andamento",
  crmSearchDeals: "Buscar",
  crmSearchDealsAria: "Buscar leads no CRM",
  crmSearchDealsPlaceholder: "Empresa, contato, CNPJ…",
  crmSearchDealsEmpty: "Nenhum negócio com esse termo.",
  crmSearchDealsSearching: "Buscando…",
  crmPhonesLabel: "Telefones",
  crmAddPhone: "Adicionar telefone",
  crmNextAction: "Próxima ação",
  crmNewPipeline: "Novo nicho",
  crmEmptyBoard:
    "Nenhum negócio neste quadro. Adicione um para começar a ligar.",
  crmNotesPlaceholder: "O que foi dito e qual o próximo passo.",
  crmContactLabel: "Sócio ou contato",
  crmSecretaryLabel: "Secretária",
  crmSecretaryName: "Nome da secretária",
  crmAddSecretary: "Adicionar secretária",
  crmCadenceTitle: "Cadência",
  crmCadenceHint:
    "Você pode renomear ou reordenar as etapas. As etapas da ficha e Descartado não saem do quadro: dá para mudar o nome, não\u00a0apagar.",
  crmAddStage: "Nova etapa",
  crmDeleteStage: "Excluir etapa",
  crmMoveDealsTo: "Mover negócios para",
  crmCompanyLabel: "Empresa",
  crmNichoLabel: "Nicho",
  crmRenamePipeline: "Renomear nicho",
  crmDeletePipeline: "Excluir nicho",
  crmDeletePipelineWarn:
    "Isso apaga o CRM deste nicho e todos os negócios.",
  crmDeletePipelineConfirm: "Apagar CRM",
  crmOpenPista: "Abrir CRM",
  crmOnGrid: "No CRM",
  crmOpenDeal: "Abrir no CRM",
  crmOpenFicha: "Abrir ficha",
  crmQualifyToEnter: "Qualifique esta empresa para ela entrar no CRM.",
  crmSaveListToEnter:
    "Salve a lista para os leads qualificados entrarem no CRM.",
  crmEnteringPista: "Colocando no CRM…",
  crmCatchUpToastOne: "1 lead das suas listas salvas entrou no CRM.",
  crmCatchUpToastMany: "{n} leads das suas listas salvas entraram no CRM.",
  crmPastFirstMile: "Daqui em diante você acompanha só no quadro, não na ficha.",
  crmFirstMileLocked: "Etapa da ficha — dá para renomear, não apagar.",
  crmBoxTitle: "Abra o CRM",
  crmBoxBody:
    "Com a lista salva, os leads que você qualificar entram sozinhos no CRM do nicho. Na ficha você avança até a reunião; o restante das etapas fica no quadro.",
  crmBoxCta: "Abrir CRM",
  crmPistaPrefix: "CRM",
  painelTitle: "Painel",
  painelHint:
    "Ligações e sequência são de hoje. Faturado e win rate seguem o recorte. Pipeline e follow-ups são o\u00a0agora.",
  painelCtaTitle: "Agora",
  painelCallsLeft: "Faltam {n} ligações para a meta de hoje.",
  painelCallsDone: "Meta de ligações do dia batida.",
  painelOverdueCta: "{n} follow-ups atrasados. Resolver no CRM.",
  painelNoNextCta: "{n} fichas sem próxima ação.",
  painelEmptyCrm: "Nenhum negócio no CRM ainda. Gere uma lista e avance as fichas.",
  painelFillAmount: "Preencha o valor nas fichas para ver o faturado.",
  painelWonWithoutAmount: "{n} ganhos sem valor",
  painelWonWithoutAmountOne: "1 ganho sem valor",
  painelTasksOverdue: "Fila de follow-up",
  painelTasksWon: "Ganhos recentes",
  painelOpenCrm: "Abrir ficha",
  painelNoOverdue: "Fila limpa. Nada atrasado.",
  painelNoWins: "Nenhum ganho neste recorte.",
  painelAllNiches: "Todos os nichos",
  painelNoTasks: "Nada atrasado e nenhum ganho neste recorte.",
  callAskEyebrow: "Confirmar",
  callAskTitle: "Ligar agora?",
  callAskBody: "Abre o telefone e conta na meta do dia.",
  callAskConfirm: "Ligar",
  callAskCancel: "Cancelar",
  callAskPending: "Ligando…",
  callConfirmHint: "Conta na meta e registra no CRM.",
  callDialHint: "Confirme para abrir o telefone e contar na meta.",
  gridCalledToday: "Ligou",
  conexoesStandbyBanner:
    "A ligação pela internet ainda não está nesta versão. Por agora, o botão Ligar abre o telefone do\u00a0aparelho.",
  conexoesStandbyEmpty:
    "Nenhuma conexão nesta conta. A montagem fica para a próxima versão.",
  conexoesStandbyForm:
    "A montagem de VoIP está pausada nesta versão. O botão Ligar abre o telefone do\u00a0aparelho.",
  conexoesInboundHint:
    "Aqui o GRID envia lista e ligação para fora. Para um formulário, anúncio ou o Make criarem negócio no CRM, use Importações.",
  importacoesTitle: "Importações",
  importacoesLead:
    "Lista de fora ou formulário. Os negócios entram no quadro — não na busca da Receita.",
  importacoesFileHint:
    "Cabeçalho bagunçado serve. Você casa cada coluna com um campo do Grid — anotações da planilha viram notas do cartão.",
  importacoesInboundHint:
    "Cole o endereço no Make, Zapier ou n8n. A chave autentica; o JSON cria o negócio no nicho acima.",
  boxLigarStandbyTitle: "Ligar pelo aparelho",
  boxLigarStandbyBody:
    "A ligação pela internet volta na próxima versão. Por agora o botão Ligar abre o telefone do\u00a0aparelho.",
  boxLigarStandbyCta: "Em breve",
  filaMontando: "Na fila — montando sua lista",
  filaPodeFechar: "Pode sair: a lista aparece em Minhas listas.",
  filaContando: "Contando — fila curta.",
  filaQualificando: "Na fila — qualificando",
  filaWorkerOcupado: "Na fila — o servidor está ocupado",
  calculadoraTitle: "Calculadora",
  calculadoraEyebrow: "Previsibilidade comercial",
  calculadoraLead:
    "Da meta de faturamento às ligações do dia. O anel do Box usa o número que você aplicar aqui.",
  calculadoraObjetivo: "Objetivo",
  calculadoraMetaFaturamento: "Meta de faturamento no período",
  calculadoraTicket: "Ticket médio do contrato",
  calculadoraPrazo: "Prazo para bater a meta (meses)",
  calculadoraTaxas: "Taxas do funil",
  calculadoraTaxa1: "Ligações com decisor → R1 realizada",
  calculadoraTaxa1Hint:
    "De cada 10 ligações com o decisor, {n} viram R1 realizada.",
  calculadoraTaxa2: "R1 realizada → R2 realizada",
  calculadoraTaxa2Hint: "De cada 10 R1 realizadas, {n} viram R2 realizada.",
  calculadoraTaxa3: "R2 realizada → Negociação",
  calculadoraTaxa3Hint:
    "De cada 10 R2 realizadas, {n} entram em negociação — não recusaram na proposta.",
  calculadoraTaxa4: "Negociação → Contrato",
  calculadoraTaxa4Hint: "De cada 10 negociações, {n} fecham contrato.",
  calculadoraUsarCrm: "Usar taxas do CRM",
  calculadoraUsarTicketCrm: "Usar ticket do CRM",
  calculadoraFunil: "Do contrato à ligação",
  calculadoraPassoContratos: "Contratos",
  calculadoraPassoNegociacoes: "Negociações",
  calculadoraPassoR2: "R2s realizadas",
  calculadoraPassoR1: "R1s realizadas",
  calculadoraPassoDecisor: "Ligações com decisor",
  calculadoraGlossario: "Glossário",
  calculadoraGlossarioLead:
    "O que conta em cada etapa: realizado, não agendado. Sem no-show, sem secretária, sem tentativa.",
  calculadoraPlano: "Plano do dia",
  calculadoraTotais: "Ligações totais (discagens)",
  calculadoraDecisor: "Ligações com decisor",
  calculadoraPorDia: "Ligações por dia",
  calculadoraPremissas:
    "Ligações totais = efetivadas × 3. O volume do dia reparte em 3 dias de prospecção por semana.",
  calculadoraCta: "Usar {n} ligações/dia no Box",
  calculadoraCtaNeed: "Preencha meta, ticket e prazo para gerar o plano.",
  calculadoraApplied: "Meta do Box atualizada.",
  calculadoraOpenBox: "Ver no Box",
  calculadoraContaLink: "Calcular pelo funil",
  boxMetaTitle: "Calcule a meta",
  boxMetaBody:
    "Quantas ligações fecham a meta no período. O anel do dia sai deste número.",
  boxMetaCta: "Abrir calculadora",
} as const;

export const CALCULADORA_GLOSSARIO = [
  {
    id: "r1-r2",
    title: "R1 e R2 no Método Pódium",
    body: "R1 é o levantamento de necessidades — a reunião de diagnóstico, realizada. R2 é a apresentação da proposta, também realizada, com base no que a R1 apurou. Agendar não conta; no-show não conta.",
  },
  {
    id: "ligacao-efetivada",
    title: "O que é ligação com o decisor",
    body: "Só conta quando você fala com quem decide. Tentativa, caixa postal, secretária e recepção ficam de fora. No plano do dia, as ligações totais já estimam esse filtro: totais = efetivadas × 3.",
  },
  {
    id: "o-que-nao-conta",
    title: "O que não entra na taxa",
    body: "Reunião agendada não é R1. Quem não apareceu não avança o funil. Contato com secretária não é ligação com decisor. A taxa mede etapa realizada → próxima etapa realizada.",
  },
  {
    id: "taxas",
    title: "Taxas de conversão por etapa",
    body: "Cada campo é o percentual de avanço: ligação com decisor → R1 realizada → R2 realizada → entrou em negociação (não recusou na proposta) → contrato. Quando uma taxa sobe, a demanda de ligações cai.",
  },
  {
    id: "ticket-meta",
    title: "Ticket médio e meta de faturamento",
    body: "Ticket é o valor médio por contrato fechado. Meta é o faturamento desejado no período. A calculadora divide um pelo outro para achar quantos contratos — e daí volta o funil até as ligações.",
  },
  {
    id: "regressivo",
    title: "Como o cálculo regressivo funciona",
    body: "Começa no objetivo (contratos) e volta etapa por etapa até as ligações com decisor. O volume do dia reparte essas discagens em 3 dias de prospecção por semana.",
  },
] as const;

export const PORTE_LABELS: Record<string, string> = {
  "01": "ME · micro",
  "03": "EPP · pequeno porte",
  "05": "Demais",
};
