/** Shared UI copy. Box and Grid stay in nav; action labels stay plain. */

export const COPY = {
  landingMetaTitle: "GRID — lista, qualificação e CRM",
  landingHeadline:
    "Monte a lista, ache quem decide e já ligue — com CRM incluso.",
  landingPromessa:
    "Nicho + cidade. Sai a lista na ordem de quem ligar, com telefone da empresa e o nome do sócio. Qualifique o digital e a lista salva cai no CRM.",
  landingPrimeiraVez: "Em minutos você sai com a lista pronta para ligar.",
  landingCtaStart: "Começar grátis",
  landingCtaPlans: "Ver planos",
  landingNavHow: "Como funciona",
  landingNavQualify: "Qualificação",
  landingNavCrm: "CRM",
  landingNavPlans: "Planos",
  landingHowEyebrow: "Como funciona",
  landingHowTitle: "Da busca à lista pronta para ligar",
  landingHowStep1Title: "Escolhe nicho e região",
  landingHowStep1Body:
    "Você define o mercado e a cidade. A busca é na Receita — não em mapa. MEI fica de fora por padrão.",
  landingHowStep2Title: "Sai a lista na ordem de quem ligar",
  landingHowStep2Body:
    "Cada linha traz telefone da empresa e o nome do sócio que decide. Ligue de cima para baixo.",
  landingHowStep3Title: "Salva, qualifica e cai no CRM",
  landingHowStep3Body:
    "Lista salva e qualificada entra sozinha no quadro. Sem copiar lead por lead.",
  landingMeiNote:
    "MEI não entra na busca padrão: faturamento ainda em desenvolvimento e menos espaço para investimentos mais robustos.",
  landingPainEyebrow: "O que trava a ligação",
  landingPainTitle: "Três tarefas lentas. A lista resolve as três.",
  landingPain1Title: "Montar a lista",
  landingPain1Body:
    "Buscar empresa por empresa, copiar telefone, jogar na planilha. Horas antes da primeira ligação.",
  landingPain2Title: "Achar quem decide",
  landingPain2Body:
    "O telefone da empresa não basta. Sem o nome do sócio, você cai na recepção ou no contador.",
  landingPain3Title: "Qualificar o digital",
  landingPain3Body:
    "Site, Instagram, Google — saber se a empresa está viva e como ela aparece online dá trabalho. E muda a ligação.",
  landingBenefitsEyebrow: "O que vem na lista",
  landingBenefitsTitle: "Telefone, quem decide, ordem de ligação",
  landingBenefit1Title: "Telefone da empresa",
  landingBenefit1Body:
    "Avisa quando o número é da contabilidade, não de quem decide.",
  landingBenefit2Title: "Sócio que decide",
  landingBenefit2Body:
    "O nome de quem pode fechar já vem na linha, para a primeira ligação.",
  landingBenefit3Title: "Ordem de quem ligar",
  landingBenefit3Body:
    "A lista já vem ranqueada. Você liga de cima para baixo.",
  landingQualifyEyebrow: "Qualificação",
  landingQualifyTitle: "Os ativos da empresa, antes de ligar",
  landingQualifyBody:
    "Cruzamos site, redes e Google com o cadastro. Telefone mais confiável e o que a empresa mostra online — para você não ligar no escuro.",
  landingQualifyPreviewLabel: "Assim sai a qualificação",
  landingCrmEyebrow: "CRM",
  landingCrmTitle: "A lista qualificada já entra no quadro",
  landingCrmBody:
    "Salvou e qualificou: o lote inteiro cai em Entrada. Você liga, anota e segue o contato — sem planilha paralela.",
  landingCrmPreviewLabel: "Assim entra no CRM",
  landingPlansEyebrow: "Planos",
  landingPlansTitle: "Escolha o plano e comece pela lista",
  landingPlansBody:
    "Buscar e ver a lista é grátis. Crédito só na exportação e na qualificação.",
  landingPlansMore: "Recargas e detalhes",
  landingPlansCtaFree: "Começar grátis",
  landingPlansCtaPaid: "Assinar",
  landingPlansFeatured: "Mais escolhido",
  landingFinalTitle: "Comece pela lista. Ligue no mesmo dia.",
  landingFinalBody:
    "Crie a conta, escolha o nicho e saia com telefone e o nome de quem decide.",
  landingPreviewLabel: "Assim sai a lista",
  landingPreviewFilter: "Clínicas · Curitiba",
  landingPreviewBuilding: "Montando a lista",
  landingPreviewReady: "Lista pronta",
  landingSignedInCta: "Abrir o GRID",
  landingSwitchAccount: "Entrar com outra conta",
  landingFooterNote: "Um produto Mundo Pódium",
  loginConfirm:
    "Enviamos um link de confirmação. Olhe a caixa de entrada e o spam. Se o e-mail estiver errado, volte e crie a conta de novo. Se já tem conta, entre.",
  loginRecover:
    "Se houver conta neste e-mail, você recebe o link para definir a senha.",
  entrarSignupLane: "Criar conta",
  entrarLoginLane: "Já tenho conta",
  entrarTrialBadge: "Treino livre",
  entrarTrialHint: "Sem cartão",
  entrarSignupHook: "Buscar e ver a lista é grátis. Sem cartão.",
  entrarLoginHook: "A lista de hoje espera. Entre e continue ligando.",
  entrarLoginCta: "Entrar no Box",
  boxPlatformCoupon:
    "Você assina o Mundo Pódium. Ative 30 dias de Piloto com o cupom no checkout.",
  boxPlatformTrialEnded:
    "Os 30 dias do Piloto acabaram. Recarregue ou assine o mesmo plano para continuar.",
  cnae: "Código da atividade da empresa na Receita.",
  decisor: "Sócio que pode decidir (quadro de sócios).",
  outrasPortas: "Outras portas",
  outrasPortasHint:
    "Quadro e nomes no site — outras pessoas além do decisor.",
  quadroReceita: "Quadro",
  nomesNoSite: "No site",
  qualifiqueNomesSite: "Qualifique para ver nomes no site.",
  nenhumNomeSite: "Nenhum diretor ou contato nomeado no site.",
  portaRecomendada: "Porta recomendada",
  score: "Ordem de quem ligar primeiro.",
  simples: "Regime Simples Nacional.",
  matriz: "Sede da empresa, não filial.",
  minutoDeOuro:
    "O mercado dele na hora: dor, meses de pico e o melhor horário. O digital fica na Qualificação.",
  clarezaDeMercado:
    "Na ficha, a Anatomia já leva o briefing: dor do ramo, meses de pico e o melhor horário.",
  anatomiaDaLigacao:
    "No capacete, nome, empresa, cidade e a promessa montam quem você é na ligação. Na ficha, o briefing do nicho — dor, calendário e ângulo — não é texto para recitar.",
  qualificacaoFicha:
    "Ativos digitais do lead: site, redes e o que falta. Isso qualifica o contato — não é o briefing da Anatomia.",
  b2c: "Vende para o consumidor final na cidade.",
  b2b: "Vende para outras empresas — indústria, serviços, logística e atacado.",
  emailGratuito: "Gmail, Hotmail e outros provedores pessoais.",
  emailSharedTitle: "E-mail compartilhado",
  emailSharedBody:
    "Aparece em várias empresas na Receita — costuma ser do contador ou do grupo, não o contato direto desta loja.",
  emailAccountantTitle: "Domínio de contabilidade",
  emailAccountantBody:
    "O endereço parece de escritório contábil. Não use como e-mail ou site da marca.",
  emailSharedAccountantTitle: "E-mail compartilhado (possível contabilidade)",
  emailSharedAccountantBody:
    "Este endereço está em mais de uma empresa e o domínio parece de escritório contábil — provavelmente não é o contato direto desta loja.",
  emailFreeTitle: "Provedor gratuito",
  emailFreeBody:
    "Gmail, Hotmail e similares — confiança menor para contato comercial.",
  dominioProprio: "E-mail @daempresa, não Gmail.",
  especialidade: "No que você é especialista.",
  area: "Em qual parte do negócio você atua.",
  comoChama: "Como você se apresenta na ligação.",
  promessa: "Uma linha do que você entrega.",
  promessaCompromisso:
    "O compromisso do dia. Entra no motivo, na consideração e no convite da reunião.",
  tratamento: "Artigo na abertura: o, a ou e.",
  novaLista: "Nova lista",
  continuarLista: "Continuar lista",
  qualificar: "Qualificar",
  qualificarMarque:
    "Selecione para cruzar site e Receita — telefone e nome mais confiáveis, e a ponte digital da ligação. 2 créditos cada. A ordem pode mudar depois.",
  qualificarEstaEmpresa: "Qualificar esta empresa",
  atualizarQualificacao: "Atualizar",
  atualizarQualificacaoHint:
    "Mantém a qualificação atual e roda de novo a auditoria (site, redes e Maps). Consome 2 créditos — só quando você pedir.",
  atualizandoQualificacao: "Atualizando…",
  corrigirQualificacao: "Corrigir",
  inserirQualificacao: "Inserir",
  limparQualificacao: "Limpar",
  salvarQualificacao: "Salvar",
  cancelarQualificacao: "Cancelar",
  corrigirQualificacaoHint: "Correção sua — não veio da Receita.",
  qualificarFichaLead: "Cruzar site, redes e Maps com a Receita.",
  qualificarFichaLeadHint:
    "Sem crawl, dor digital e selos Confirmado/Atualizado ficam vazios — isso não significa que a empresa “não tem dor”.",
  qualificarBeneficioTelefone:
    "Telefone cruzado (site × Receita) e selo de conferência",
  qualificarBeneficioContato:
    "Contato e decisor mais atuais que o cadastro sozinho",
  qualificarBeneficioDigital:
    "Cards dos ativos: site, redes e lacunas pra cruzar o lead — não o pitch",
  boxSemLista:
    "Salve a lista para abrir a pista. Qualificar e ligar vêm na volta — salvar não substitui ligar.",
  boxPistaFechada: "Pista fechada",
  boxSequenciaHintZero:
    "Nenhuma sequência ainda. Ligue hoje para começar.",
  boxSequenciaHintOne:
    "Você está numa sequência de 1 dia fazendo ligações.",
  boxSequenciaHintMany:
    "Você está numa sequência de {n} dias fazendo ligações.",
  boxAcessoHint: "Você ainda possui {n} créditos.",
  boxListasHintZero: "Você não tem listas salvas.",
  boxListasHintOne: "Você possui 1 lista salva.",
  boxListasHintMany: "Você possui {n} listas salvas.",
  boxEstrutura: "Estrutura",
  boxPularEtapa: "Pular etapa",
  ajustarBusca: "Ajustar busca",
  ajustar: "Ajustar",
  ajustarNichoQualidade: "Ajustar nicho e qualidade",
  verNovoGrid: "Ver novo grid",
  verResultados: "Ver resultados",
  listaOriginalNaoSome: "A lista original não some",
  largadaNovaHint:
    "Monte a lista em 3 passos: o que buscar, onde, e a qualidade do contato.",
  largadaContinuarHint:
    "As escolhas desta sessão ainda estão aqui. Continue nos 3 passos — nada foi apagado.",
  largadaAjustarHint:
    "As escolhas desta lista já estão preenchidas. Mude nicho, região ou qualidade e gere um grid novo — a lista original não some.",
  gridEmptyAdjust:
    "Nenhum lead nesta busca. Ajuste nicho, região ou qualidade — as escolhas atuais já vêm preenchidas.",
  gridLigarOrdem: "ligar nesta ordem",
  salvarLista: "Salvar lista",
  salvarNaPista: "Salvar na pista",
  salvarEstaLista: "Salvar esta lista",
  renomearLista: "Renomear lista",
  listaSalva: "Salva",
  salvarMotivoListas: "Fica em Minhas listas para abrir de novo",
  salvarMotivoOrdem: "A ordem P1, P2, P3 continua",
  salvarMotivoCrm: "Qualificados entram sozinhos na pista do CRM",
  tirarDaLista: "Tirar da lista",
  tirarDaListaConfirm: "Tirar esta empresa da lista? O negócio no CRM fica.",
  listaDaVolta: "Lista da volta",
  listaDaVoltaFallback: "Esta lista não tem P novo — usando outra.",
  empresaForaDaBase: "Este CNPJ não está nesta base da Receita.",
  empresasPlaceholder: "Nome, fantasia ou CNPJ",
  empresasMinChars: "Digite nome, fantasia ou CNPJ.",
  tirarDasListas: "Tirar das listas",
  listasNaoSalvas: "Não salvas",
  listasRascunho: "Rascunho",
  listasSalvasHint:
    "As que você guardou para ligar de novo. Tirar daqui não apaga a lista.",
  listasNaoSalvasHint:
    "Até 3 rascunhos. Só dá para abrir — salve para guardar ou excluir.",
  listasMostrarMais: "Mostrar mais · {n}",
  listasLeadOne: "lead",
  listasLeadMany: "leads",
  crmNav: "CRM",
  crmTitle: "Pista de negócios",
  crmHint:
    "Cada faixa é uma volta. Arraste o card, registre a ligação e marque a próxima.",
  crmOpening: "Abrindo pista…",
  crmOpeningNav: "Abrindo…",
  crmLoadingNicho: "Abrindo nicho…",
  crmAddDeal: "Adicionar negócio",
  crmAdjustCadence: "Ajustar cadência",
  crmNoActivity: "Sem volta marcada",
  crmLogCall: "Salvar",
  crmLogCallHint:
    "Guarda no histórico. Se houver data, deixa a próxima no card.",
  crmSchedule: "Só agendar próxima",
  crmScheduleHint:
    "Atualiza data e ação no card. Não registra a ligação.",
  crmComposerPlaceholder: "O que considerar nesta ação?",
  crmHistoryTitle: "Histórico",
  crmHistoryTodo: "A fazer",
  crmHistoryTodoToday: "Hoje",
  crmHistoryTodoOverdue: "Atrasada",
  crmMarkDone: "Concluir",
  crmHistoryEmpty: "Nada registrado ainda. Cada ligação e ação fica aqui.",
  crmCreatedAt: "Criada",
  crmSaveHistory: "Salvar",
  crmNoDeadline: "Sem prazo",
  crmSetDeadline: "Agendar prazo",
  crmDeadlineLabel: "Prazo",
  crmTimeLabel: "Horário",
  crmToday: "Hoje",
  crmTomorrow: "Amanhã",
  crmWeekLater: "1 semana depois",
  crmPrevStages: "Fases anteriores",
  crmNextStages: "Próximas fases",
  crmPeopleTitle: "Pessoas",
  crmAddPerson: "Adicionar pessoa",
  crmPersonEmail: "E-mail",
  crmPersonPhone: "Telefone",
  crmCompanyPhone: "Telefone da empresa",
  crmActions: "Ações",
  crmCallNow: "Ligar",
  crmWhatsappNow: "WhatsApp",
  crmNoteNow: "Nota",
  crmEmailNow: "E-mail",
  crmNoPhone: "Adicione um telefone para ligar.",
  crmOutcomeOpen: "Em andamento",
  crmOutcomeWon: "Ganho",
  crmOutcomeLost: "Perdido",
  crmShowClosed: "Ganhos / perdidos",
  crmHideClosed: "Só em andamento",
  crmPhonesLabel: "Telefones",
  crmAddPhone: "Adicionar telefone",
  crmNextAction: "Próxima volta",
  crmNewPipeline: "Novo nicho",
  crmEmptyBoard:
    "Nenhum negócio nesta pista. Adicione um para começar a ligar.",
  crmNotesPlaceholder: "O que foi dito e qual o próximo passo.",
  crmContactLabel: "Sócio ou contato",
  crmSecretaryLabel: "Secretária",
  crmSecretaryName: "Nome da secretária",
  crmAddSecretary: "Adicionar secretária",
  crmCadenceTitle: "Cadência",
  crmCadenceHint:
    "Renomeie ou reordene. As faixas da ficha e Descartado ficam — dá para mudar o nome, não apagar.",
  crmAddStage: "Nova faixa",
  crmDeleteStage: "Excluir faixa",
  crmMoveDealsTo: "Mover negócios para",
  crmCompanyLabel: "Empresa",
  crmNichoLabel: "Nicho",
  crmRenamePipeline: "Renomear nicho",
  crmDeletePipeline: "Excluir nicho",
  crmDeletePipelineWarn:
    "Isso apaga a pista e todos os negócios deste nicho.",
  crmDeletePipelineConfirm: "Apagar pista",
  crmOpenPista: "Abrir pista",
  crmOnGrid: "No CRM",
  crmOpenDeal: "Abrir no CRM",
  crmOpenFicha: "Abrir ficha",
  crmQualifyToEnter: "Qualifique para entrar na pista.",
  crmSaveListToEnter:
    "Só lista salva manda qualificado à pista. Sem salvar, o CRM não recebe.",
  crmEnteringPista: "Colocando na pista…",
  crmCatchUpToastOne: "1 lead das suas listas salvas entrou na pista.",
  crmCatchUpToastMany: "{n} leads das suas listas salvas entraram na pista.",
  crmPastFirstMile: "A partir daqui a pista continua no CRM.",
  crmFirstMileLocked: "Faixa da ficha — dá para renomear, não apagar.",
  crmBoxTitle: "Abra a pista",
  crmBoxBody:
    "Leads qualificados entram sozinhos na pista do nicho. A ficha movimenta até a reunião; o restante fica no CRM.",
  crmBoxCta: "Abrir CRM",
  crmPistaPrefix: "Pista",
  conexoesStandbyBanner:
    "Conexões em stand-by nesta primeira onda. Ligar usa o telefone do aparelho. VoIP nativo volta em seguida.",
  conexoesStandbyEmpty:
    "Nenhuma conexão nesta conta. A montagem fica para a próxima onda.",
  conexoesStandbyForm:
    "A montagem de VoIP está pausada nesta onda. O botão Ligar abre o telefone do aparelho.",
  boxLigarStandbyTitle: "Ligar pelo aparelho",
  boxLigarStandbyBody:
    "VoIP nativo volta na próxima onda. Por agora o botão Ligar abre o telefone do aparelho.",
  boxLigarStandbyCta: "Em breve",
  filaMontando: "Na fila — montando sua lista",
  filaPodeFechar: "Pode sair: a lista aparece em Minhas listas.",
  filaContando: "Contando — fila curta.",
  filaQualificando: "Na fila — qualificando",
  filaWorkerOcupado: "Na fila — worker ocupado",
} as const;

export const PORTE_LABELS: Record<string, string> = {
  "01": "ME · micro",
  "03": "EPP · pequeno porte",
  "05": "Demais",
};
